### PR TITLE
Initial add of fuzz

### PR DESCRIPTION
**Pull request by andybons**
Beginnings of https://docs.google.com/document/u/1/d/1zXR-TFL3BfnceEAWytV8bnzB2Tfp6EPFinWVJ5V4QC8/pub

Currently only works with a single package as an argument.
Heavily based on the go test command architecture.

Update dvyukov/go-fuzz#154

### CODE REVIEW

**Comment by andybons** [comment]
To be clear, the desired API is to have `Fuzz*` functions live within `*_test.go` files. @ianlancetaylor and I are chatting on how to make that happen. I chose tags and `*_fuzz.go` for ease of the initial implementation.

He suggested we generate a `_test.go` file with an entrypoint like TestFuzzer(t *testing.T) {...} that will actually run the tests, and instead of running `go build` on the generated main file, run `go test` in the package after the generated `_test.go` file is written.

As I understand it, this would require writing a file into the src tree of the package, or we’d have to copy the whole package somewhere.

**Comment by dvyukov** [comment]
> He suggested we generate a _test.go file with an entrypoint like ...

Is it meant to be only a temporal solution until we integrate with testing package? I think that testing package should be able to call Fuzz functions without any problems, right?
Source generation is pain, that's what go-fuzz-build does now, and it's hard to use with bazel. One of the goals of this new support was to get rid of it.

**Comment by ianlancetaylor** [comment]
Yes, just a temporary solution (I know it was a mistake but I do like the idea of referring to it as a temporal solution--temporal means "of the world rather than of the divine").  If we're doing a trial in a separate binary, I think it ought to be as close to the final desired API as possible, and I think the final desired API is to have Fuzz functions in _test.go files.  The generated file is only needed so that `go test` will pick it up.

**Comment by dvyukov** [comment]
Sounds good then.
Yes, we want them in test files so that they are at least built. But even without corpus, they can be used as useful tests, we can just give them N random inputs. If corpus is discoverable, we can run all inputs from corpus even in normal test mode, which is useful regression testing.

**Comment by andybons** [comment]
OK. Updated the logic to create a temporary `_test.go` file in the package directory (to be removed once fuzzing is complete). Code is a bit rough but let me know how you feel about this approach.

**Comment by dvyukov** [comment]
But this is a temporary solution, right? Just to make the prototype work. If so, any approach will do IMHO.

**Comment by andybons** [comment]
@dvyukov yes that’s correct.

**Pull request merged**
